/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signIn` | `/signIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signUp` | `/signUp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/done` | `/done`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/personalInfo` | `/personalInfo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/preferences` | `/preferences`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/scheduleInfo` | `/scheduleInfo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/activity` | `/activity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signIn` | `/signIn`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signUp` | `/signUp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/done` | `/done`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/personalInfo` | `/personalInfo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/preferences` | `/preferences`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/scheduleInfo` | `/scheduleInfo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/welcome` | `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/activity` | `/activity`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signIn${`?${string}` | `#${string}` | ''}` | `/signIn${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signUp${`?${string}` | `#${string}` | ''}` | `/signUp${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/done${`?${string}` | `#${string}` | ''}` | `/done${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/personalInfo${`?${string}` | `#${string}` | ''}` | `/personalInfo${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/preferences${`?${string}` | `#${string}` | ''}` | `/preferences${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/scheduleInfo${`?${string}` | `#${string}` | ''}` | `/scheduleInfo${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/welcome${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/activity${`?${string}` | `#${string}` | ''}` | `/activity${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signIn` | `/signIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signUp` | `/signUp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/done` | `/done`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/personalInfo` | `/personalInfo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/preferences` | `/preferences`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/scheduleInfo` | `/scheduleInfo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/activity` | `/activity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
